# coding=utf-8
# ----------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License file in the project root for license information.
# ----------------------------------------------------------------------------------------------

PIPELINE_INPUT_STAGE_PROPERTIES = {
        "input/http@v1": [
            # (property name, required)
            ("type", True),
            ("url", True),
            ("method", False),
            ("format", True),
            ("request", False),
            ("authentication", False),
            ("interval", True),
            ("partitionCount", True),
            ("partitionStrategy", True),
            ("id", False),
            ("name", False),
            ("next", True)
        ],
        "input/influxdbv2@v1": [
            ("type", True),
            ("query", True),
            ("query.expression", True),
            ("url", True),
            ("interval", True),
            ("port", False),
            ("organization", True),
            ("format", True),
            ("partitionCount", True),
            ("partitionStrategy", True),
            ("authentication", True),
            ("id", False),
            ("name", False),
            ("next", True)
        ],
        "input/mqtt@v1": [
            ("type", True),
            ("broker", True),
            ("qos", False),
            ("cleanSession", False),
            ("topics", True),
            ("authentication", False),
            ("format", True),
            ("partitionCount", True),
            ("partitionStrategy", True),
            ("id", False),
            ("name", False),
            ("next", True)
        ],
        "input/sqlserver@v1": [
            ("type", True),
            ("query", True),
            ("query.expression", True),
            ("server", True),
            ("database", True),
            ("interval", True),
            ("port", False),
            ("format", True),
            ("partitionCount", True),
            ("partitionStrategy", True),
            ("authentication", False),
            ("id", False),
            ("name", False),
            ("next", True)
        ],
    }

PIPELINE_PROCESSOR_STAGE_PROPERTIES = {
    "processor/aggregate@v1": [
        ("windowType", True),
        ("windowSize", True),
        ("function", True),
        ("inputPath", True),
        ("outputPath", True),
        ("type", False),
        ("id", False),
        ("name", False),
        ("next", True)
    ],
    "processor/enrich@v1": [
        ("dataset", True),
        ("outputPath", True),
        ("conditions", False),
        ("conditions.type", True),
        ("conditions.key", False),
        ("conditions.inputPath", True),
        ("alwaysArray", False),
        ("limit", False),
        ("type", False),
        ("id", False),
        ("name", False),
        ("next", True)
    ],
    "processor/filter@v1": [
        ("expression", True),
        ("type", False),
        ("id", False),
        ("name", False),
        ("next", True)
    ],
    "processor/grpc@v1": [
        ("serverAddress", True),
        ("rpcName", True),
        ("descriptor", True),
        ("request", False),
        ("request.body", False),
        ("request.metadata", False),
        ("response", False),
        ("response.body", False),
        ("response.metadata", False),
        ("response.status", False),
        ("type", False),
        ("id", False),
        ("name", False),
        ("next", True)
    ],
    "processor/http@v1": [
        ("url", True),
        ("method", True),
        ("request", False),
        ("request.body", False),
        ("request.headers", False),
        ("response", False),
        ("response.body", False),
        ("response.headers", False),
        ("response.status", False),
        ("type", False),
        ("id", False),
        ("name", False),
        ("next", True)
    ],
    "processor/lkv@v1": [
        ("properties", True),
        ("properties.inputPath", True),
        ("properties.outputPath", True),
        ("properties.timestampOutputPath", False),
        ("properties.ttl", False),
        ("type", False),
        ("id", False),
        ("name", False),
        ("next", True)
    ],
    "processor/transform@v1": [
        ("expression", True),
        ("type", False),
        ("id", False),
        ("name", False),
        ("next", True)
    ],
}

PIPELINE_OUTPUT_STAGE_PROPERTIES = {
    "output/blobstorage@v1": [
        ("type", True),
        ("accountName", True),
        ("containerName", True),
        ("authentication", True),
        ("format", True),
        ("blobPath", False),
        ("batch", False),
        ("retry", False),
        ("id", False),
        ("name", False),
    ],
    "output/dataexplorer@v1": [
        ("type", True),
        ("clusterUrl", True),
        ("database", True),
        ("table", True),
        ("authentication", True),
        ("batch", False),
        ("columns", True),
        ("columns.name", True),
        ("columns.path", False),
        ("retry", False),
        ("id", False),
        ("name", False),
    ],
    "output/fabric@v1": [
        ("type", True),
        ("workspace", True),
        ("lakehouse", True),
        ("table", True),
        ("filePath", False),
        ("authentication", True),
        ("batch", False),
        ("columns", True),
        ("columns.name", True),
        ("columns.type", True),
        ("columns.path", False),
        ("retry", False),
        ("id", False),
        ("name", False),
    ],
    "output/file@v1": [
        ("type", True),
        ("rootDirectory", True),
        ("filePath", False),
        ("batch", False),
        ("format", True),
        ("filePermissions", False),
        ("id", False),
        ("name", False),
    ],
    "output/grpc@v1": [
        ("type", True),
        ("serverAddress", True),
        ("rpcName", True),
        ("descriptor", True),
        ("request", False),
        ("request.body", False),
        ("request.metadata", False),
        ("retry", False),
        ("authentication", False),
        ("tls", False),
        ("id", False),
        ("name", False),
    ],
    "output/http@v1": [
        ("type", True),
        ("url", True),
        ("method", True),
        ("request", False),
        ("request.body", False),
        ("request.headers", False),
        ("retry", False),
        ("authentication", False),
        ("id", False),
        ("name", False),
    ],
    "output/mqtt@v1": [
        ("type", True),
        ("broker", True),
        ("qos", False),
        ("topic", True),
        ("authentication", False),
        ("format", True),
        ("userProperties", False),
        ("retry", False),
        ("id", False),
        ("name", False),
    ],
    "output/refdata@v1": [
        ("type", True),
        ("dataset", True),
    ],
}